---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Kite UD summaries

## Prepare packages

```{r}
# load libraries
# for spatial data and data handling
library(sf)
library(dplyr)

# mapping and visualisation
library(ggplot2)
```

```{r}
# install package for high resolution map data
# if it is not already installed; if installed load it
if(!require("rnaturalearthhires")) {
  devtools::install_github("ropensci/rnaturalearthhires")
}
```

## Prepare kite data

```{r}
# list kite shapefiles
kites = st_layers(dsn = "data/Kite shapefiles/")

# read in kite shapefiles as a list of sf objects
kites = lapply(
  kites$name, function(l) {
    st_read(
      dsn = "data/Kite shapefiles/",
      layer = l
    )
  }
)

# convert all to geographic coordinates for uniformity
kites = lapply(kites, st_transform, crs = 4326)

# combine list into a single sf object
kites = dplyr::bind_rows(kites)

# arrange by name and core status
kites = arrange(
  kites,
  CORE.
)

# set factor levels
kites$CORE. = factor(
  kites$CORE., levels = c("95%", "50%")
)
```

## Get map base layer

```{r}
# plot kite UDs over europe
# first get europe
countries = st_as_sf(rnaturalearthhires::countries10)

# includes russia, guyana and bits; crop
# set bounds at iceland to the north, and israel to the east
eu_bounds = filter(
  countries, NAME %in% c("Iceland", "Israel")
) |> 
  st_bbox() |> 
  st_as_sfc()

# crop by polygon
eu = st_crop(
  countries, eu_bounds
)

# check CRS match between datasets, this is a shallow match
assertthat::assert_that(
  st_crs(kites) == st_crs(eu)
)
```

## Plot kite UDs on map

```{r}
# plot kites on maps
ggplot()+
  geom_sf(
    data = eu,
    col = "grey",
    size = 0.1
  ) +
  geom_sf(
    data = kites,
    aes(
      fill = `CORE.`
    ),
    alpha = 1
  ) +
  scale_fill_viridis_d(
    direction = -1,
    limits = c("95%", "50%")
  )+
  theme_bw()+
  coord_sf(
    crs = 32631, # choose a good projection for western EU
    expand = F
  )
```

## Load PA files

```{r}
# read in data
pa_types = st_layers(
  "data/Protected areas shapefiles/"
)

# read in as list
pa = lapply(
  pa_types$name, function(l) {
    pa_ = st_read(
      dsn = "data/Protected areas shapefiles/",
      layer = l
    ) |> 
      mutate(
        pa_type = l
      )
    
    # cast to simple polygons to improve processing
    pa_ = st_cast(pa_, "POLYGON")
    
    pa_
  }
)

# all pas have the same crs, which is also WGS84 (4326)

# merge PAS into a single object, combining by type
pa = dplyr::bind_rows(pa)
```

```{r}
# repairing spherical geometries
sf::sf_use_s2(FALSE)
```

## Calculate overlap with kite UDs

```{r}
# get overlap between kites and pas, separately per PA type
overlap = st_intersection(kites, pa)

# get area of each overlap
overlap = mutate(
  overlap,
  area = as.numeric(st_area(overlap) / (1000 * 1000)) # in km2
)

# summarise overlap by kite id and protected area type
overlap_summary = st_drop_geometry(
  overlap
) |> 
group_by(
  ID, CORE., pa_type
) |> 
  summarise(
    overlap_area = sum(area)
  )
```

## Link PA overlap with kite UD area

```{r}
# get actual kite UD area
kite_area = kites |> 
  mutate(
    ud_area = as.numeric(st_area(kites) / (1000 * 1000)) # in km2
  )

# prep for joining to overlap
kite_area = st_drop_geometry(kite_area) |> 
  select(ID, CORE., ud_area)

# some kite UDs are in multiple parts, sum
kite_area = kite_area |> 
  group_by(ID, CORE.) |> 
  summarise(
    ud_area = sum(ud_area)
  )

# join the overlap data and kite UD area
overlap_summary =
  overlap_summary |> 
  select(
    ID, CORE., pa_type, overlap_area
  ) |> 
  left_join(
    kite_area, 
    by = c(
      "ID", "CORE."
    )
  )

# save data
readr::write_csv(
  overlap_summary,
  file = "data/overlap_summary.csv"
)
```

## Total UD in protected areas

```{r}
# combine spatial overlaps into single features by ID
total_overlap = overlap |> 
  group_by(
    ID, CORE.
  ) |> 
  summarise()

# get total area of the overlap, regardless of pa_type
total_overlap = ungroup(total_overlap) |> 
  mutate(
    total_pa_overlap = as.numeric(st_area(total_overlap)) / (1000 * 1000)
)

# drop geomtery and prepare for joining with kite UD area
total_overlap = st_drop_geometry(total_overlap)
```

```{r}
# join total pa overlap with total ud area
total_pa_overlap = left_join(
  kite_area, total_overlap
)

# save to file
readr::write_csv(
  total_pa_overlap, file = "data/total_pa_overlap.csv"
)
```
