---
editor_options: 
  chunk_output_type: console
---

```{r}
library(sf)
library(dplyr)
library(tidyr)
library(assertthat)
```

## Load PA files

```{r}
# read in data
pa_types <- st_layers(
  "data/protected-areas-data/"
)

# read in as list
pa <- lapply(
  pa_types$name, function(l) {
    pa_ <- st_read(
      dsn = "data/protected-areas-data/",
      layer = l
    ) |>
      mutate(
        pa_type = l
      )

    # cast to simple polygons to improve processing
    pa_ <- st_cast(pa_, "POLYGON")

    pa_
  }
)

# all PAs do not have the same CRS, convert to UTM 33N
pa <- lapply(pa, st_transform, 3035)

# merge PAS into a single object, combining by type
pa <- dplyr::bind_rows(pa)

# save to check in QGIS
st_write(
  pa,
  dsn = "pa_laea.gpkg", append = FALSE
)
```

## Load kite geopackages

```{r}
# list kite files
kite_sf <- st_read("data/kite_sf.gpkg")

# cast to 3035
kite_sf <- st_transform(kite_sf, 3035)

st_write(
  kite_sf,
  dsn = "kite_ud_laea.gpkg", append = FALSE
)
```

```{r}
# repairing spherical geometries
sf::sf_use_s2(FALSE)
```

## Calculate overlap with kite UDs

```{r}
# get overlap between kites and pas, separately per PA type
overlap <- st_intersection(kite_sf, pa)

# group and summarise
overlap <- group_by(
  overlap,
  kite_id, kde_percent, year_start, year_end, pa_type
) |>
  summarise()

# get area of each overlap
overlap <- ungroup(overlap) |>
  mutate(
    overlap,
    area = as.numeric(st_area(overlap) / (1000 * 1000)) # in km2
  )

# summarise overlap by kite id and protected area type
overlap_summary <- st_drop_geometry(
  overlap
) |>
  as_tibble() |>
  rename(
    overlap_area = area
  )
```

## Link PA overlap with kite UD area

```{r}
# join the overlap data and kite UD area
overlap_summary <-
  overlap_summary |>
  st_drop_geometry()

# get combinations of kite ids and pa type
kite_pa_combinations <- crossing(
  select(overlap_summary, kite_id),
  tibble(pa_type = unique(overlap_summary$pa_type))
)

# join combinations data with overlap data
overlap_summary <- left_join(kite_pa_combinations, overlap_summary)

# join combined data with UD data
overlap_summary <- left_join(
  st_drop_geometry(kite_sf),
  overlap_summary
) |>
  rename(ud_area = area) |>
  mutate(
    overlap_area = if_else(
      is.na(overlap_area), 0, overlap_area
    )
  ) |>
  as_tibble()

# data now has zeros for PA types in each year if the kite
# did not overlap with that type

# check that all overlap areas are less than or equal to 1.0
assert_that(
  all((overlap_summary$overlap_area / overlap_summary$ud_area) <= 1.0)
)

# check proportions that are > 1.0
(overlap_summary$overlap_area / overlap_summary$ud_area)[
  (overlap_summary$overlap_area / overlap_summary$ud_area) > 1.0
]

# issue appears to be at the level of 6 decimal places or more,
# probably safe to take these values as 1.0
# issue likely caused by calculating UD area before transforming to
# EPSG:3035 LAEA

# save data
readr::write_csv(
  overlap_summary,
  file = "data/overlap_summary.csv"
)
```

## Total UD in protected areas

```{r}
# combine spatial overlaps into single features by ID
total_overlap <- overlap |>
  group_by(
    kite_id, kde_percent, year_start, year_end
  ) |>
  summarise()

# get total area of the overlap, regardless of pa_type
total_overlap <- ungroup(total_overlap) |>
  mutate(
    total_pa_overlap = as.numeric(st_area(total_overlap)) / (1000 * 1000)
  )

# drop geomtery and prepare for joining with kite UD area
total_overlap <- st_drop_geometry(total_overlap)
```

```{r}
# join total pa overlap with total ud area
total_pa_overlap <- left_join(
  st_drop_geometry(kite_sf), total_overlap
) |>
  select(-id) |>
  as_tibble() |>
  mutate(
    total_pa_overlap = if_else(is.na(total_pa_overlap), 0, total_pa_overlap)
  ) |>
  rename(ud_area = area)

# check that overlaps are not greater than 1.0
assert_that(
  all(
    (total_pa_overlap$total_pa_overlap / total_pa_overlap$ud_area) <= 1
  )
)

# save to file
readr::write_csv(
  total_pa_overlap,
  file = "data/total_pa_overlap.csv"
)
```
